package com.capstone.yafood.utils

const val RESULT_SNAP = "RESULT_SNAP"
const val RECIPE_ID = "RECIPE_ID"
const val RECIPE_IMAGE = "RECIPE_IMAGE"
const val RECIPE_TITLE = "RECIPE_TITLE"
const val RECIPE_INGREDIENT = "RECIPE_INGREDIENT"
const val RECIPE_STEP = "RECIPE_STEP"

const val ARTICLE_ID = "ARTICLE_ID"
const val ARTICLE_TITLE = "ARTICLE_TITLE"
const val ARTICLE_IMAGE = "ARTICLE_IMAGE"
const val ARTICLE_INGREDIENT = "ARTICLE_INGREDIENT"
const val ARTICLE_STEP = "ARTICLE_STEP"
const val ARTICLE_USER_ID = "ARTICLE_USER_ID"
const val ARTICLE_USER_NAME = "ARTICLE_USER_NAME"
const val ARTICLE_USER_IMAGE = "ARTICLE_USER_IMAGE"